// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieShareCore.Data.Repositories;

namespace MovieShareCore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200708105015_AddRequiredToCountryIdAndDirectorIdAllEntities")]
    partial class AddRequiredToCountryIdAndDirectorIdAllEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MovieShareCore.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BO",
                            Name = "Bolivia, Plurinational State of"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BQ",
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 33,
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 42,
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44,
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 49,
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 50,
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CD",
                            Name = "Congo, the Democratic Republic of the"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 54,
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 55,
                            Code = "CI",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 56,
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 57,
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 58,
                            Code = "CW",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 59,
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 60,
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 61,
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 62,
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 63,
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 64,
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 65,
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 66,
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 67,
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 68,
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 69,
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 70,
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 71,
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 72,
                            Code = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 73,
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 74,
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 75,
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 76,
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 77,
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 78,
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 79,
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 80,
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 81,
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 83,
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 84,
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 90,
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 93,
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 94,
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 95,
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 96,
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 97,
                            Code = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 98,
                            Code = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 99,
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 100,
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 101,
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 102,
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 103,
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 104,
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 105,
                            Code = "IR",
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            Id = 106,
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 107,
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 108,
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 109,
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 110,
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 111,
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 112,
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 113,
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 114,
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 115,
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 116,
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 117,
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 118,
                            Code = "KP",
                            Name = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            Id = 119,
                            Code = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Id = 120,
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 121,
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 122,
                            Code = "LA",
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 123,
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 124,
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 125,
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 126,
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 127,
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 128,
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 130,
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 131,
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 132,
                            Code = "MK",
                            Name = "Macedonia, the former Yugoslav Republic of"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 134,
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 135,
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 136,
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 137,
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 138,
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 140,
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 141,
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 142,
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 143,
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 144,
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 145,
                            Code = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 146,
                            Code = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Id = 147,
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 148,
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 149,
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 150,
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 151,
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 152,
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 153,
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 154,
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 155,
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 156,
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 157,
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 158,
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 159,
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 160,
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 161,
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 162,
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 163,
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 164,
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 165,
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 166,
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 167,
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 168,
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 169,
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 170,
                            Code = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            Id = 171,
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 172,
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 173,
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 174,
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 175,
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 176,
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 177,
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 178,
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 179,
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 180,
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 181,
                            Code = "RE",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 182,
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 183,
                            Code = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 184,
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 185,
                            Code = "BL",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 186,
                            Code = "SH",
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = 187,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 188,
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 189,
                            Code = "MF",
                            Name = "Saint Martin (French part)"
                        },
                        new
                        {
                            Id = 190,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 191,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 192,
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 193,
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 194,
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 195,
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 196,
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 197,
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 198,
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 199,
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 200,
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 201,
                            Code = "SX",
                            Name = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            Id = 202,
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 203,
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 204,
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 205,
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 206,
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 207,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 208,
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 209,
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 210,
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 211,
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 212,
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 213,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 214,
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 215,
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 216,
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 217,
                            Code = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Id = 218,
                            Code = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            Id = 219,
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 220,
                            Code = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 221,
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 222,
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 224,
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 225,
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 226,
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 227,
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 228,
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 229,
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 230,
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 231,
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 232,
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 233,
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 234,
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 235,
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 236,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 237,
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 238,
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 239,
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 240,
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 241,
                            Code = "VE",
                            Name = "Venezuela, Bolivarian Republic of"
                        },
                        new
                        {
                            Id = 242,
                            Code = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 243,
                            Code = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Id = 244,
                            Code = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Id = 245,
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 246,
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 247,
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 248,
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 249,
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("MovieShareCore.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Admin = true,
                            Birthdate = new DateTime(2020, 7, 8, 11, 50, 15, 122, DateTimeKind.Local).AddTicks(7062),
                            CountryId = 53,
                            Mail = "mail1@sample.com",
                            Name = "Malanga Yuca Frita"
                        },
                        new
                        {
                            Id = 6,
                            Admin = true,
                            Birthdate = new DateTime(2020, 7, 8, 11, 50, 15, 127, DateTimeKind.Local).AddTicks(5089),
                            CountryId = 55,
                            Mail = "mail2@sample.com",
                            Name = "Julio Pérez"
                        },
                        new
                        {
                            Id = 7,
                            Admin = true,
                            Birthdate = new DateTime(2020, 7, 8, 11, 50, 15, 127, DateTimeKind.Local).AddTicks(5181),
                            CountryId = 5,
                            Mail = "mail3@sample.com",
                            Name = "Haliam Pérez"
                        });
                });

            modelBuilder.Entity("MovieShareCore.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Knowfor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1946, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 24,
                            Knowfor = "Schindler's List",
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1942, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 23,
                            Knowfor = "Taxi Driver",
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1899, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 22,
                            Knowfor = "Psycho",
                            Name = "Alfred Hitchcock"
                        },
                        new
                        {
                            Id = 6,
                            Birthdate = new DateTime(1982, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 21,
                            Knowfor = "Marina",
                            Name = "Haliam Pérez"
                        },
                        new
                        {
                            Id = 10,
                            Birthdate = new DateTime(1928, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 20,
                            Knowfor = "Memorias del Subdesarrollo",
                            Name = "Tomás Gutierres Alea"
                        });
                });

            modelBuilder.Entity("MovieShareCore.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "FilmNoir"
                        },
                        new
                        {
                            Id = 11,
                            Name = "History"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mistery"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 16,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 19,
                            Name = "War"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("MovieShareCore.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Budget")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Budget = 250000,
                            CountryId = 15,
                            DirectorId = 2,
                            Duration = 81,
                            GenreId = 9,
                            ReleaseDate = new DateTime(1931, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "City Lights"
                        },
                        new
                        {
                            Id = 6,
                            Budget = 8000000,
                            CountryId = 14,
                            DirectorId = 2,
                            Duration = 153,
                            GenreId = 1,
                            ReleaseDate = new DateTime(1994, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Budget = 2500000,
                            CountryId = 13,
                            DirectorId = 2,
                            Duration = 128,
                            GenreId = 1,
                            ReleaseDate = new DateTime(1958, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Vertigo"
                        },
                        new
                        {
                            Id = 10,
                            Budget = 5000000,
                            CountryId = 12,
                            DirectorId = 2,
                            Duration = 207,
                            GenreId = 1,
                            ReleaseDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The seven Samurai"
                        },
                        new
                        {
                            Id = 11,
                            Budget = 15000000,
                            CountryId = 11,
                            DirectorId = 2,
                            Duration = 135,
                            GenreId = 1,
                            ReleaseDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Roma"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieShareCore.Models.Customer", b =>
                {
                    b.HasOne("MovieShareCore.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieShareCore.Models.Director", b =>
                {
                    b.HasOne("MovieShareCore.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieShareCore.Models.Movie", b =>
                {
                    b.HasOne("MovieShareCore.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieShareCore.Models.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieShareCore.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
